apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowershop
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: flowershop
  template:
    metadata:
      labels:
        app: flowershop
    spec:
      containers:
        - name: flowershop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
