apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flowershop-app
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: flowershop
  source:
    repoURL: 'https://github.com/OletiSatishKumar/K8S_Capstone.git'
    targetRevision: master
    path: infra/helm/flowershop
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
