name: Update Infra with New Image Tag

on:
  repository_dispatch:
    types: [update_infra]

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update dev-values.yaml
        run: |
          sed -i "s|tag: .*|tag: ${{ github.event.client_payload.tag }}|" dev-values.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag to ${{ github.event.client_payload.tag }}"
          git push
