name: Update Helm Values

on:
  repository_dispatch:
    types: [update_infra]

jobs:
  update-values:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get image tag from payload
        run: echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV

      - name: Update dev-values.yaml with new image tag
        run: |
          sed -i "s/tag: .*/tag: $IMAGE_TAG/" helm/dev-values.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/dev-values.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
